# Generated by Django 4.0.5 on 2022-07-04 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='owner',
            table='owners',
        ),
    ]
